version: "3.8"

services:
  php:
    build: php
    working_dir: /app
    environment:
      - HOME=/tmp
    user: "${UID}:${GID}"
    userns_mode: host
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - ../:/app
      - ../.cache/composer:/tmp/.composer/cache
    tmpfs:
      - /tmp
    depends_on:
      - mariadb

  nginx:
    build:
      context: nginx
    ports:
      - "${PORT}:8080"
    volumes:
      - ../public:/app/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    tmpfs:
      - /tmp
    depends_on:
      - php

  mariadb:
    image: mariadb:11.3
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    tmpfs:
      - /tmp
      - /var/lib/mysql

  phpmyadmin:
    profiles: ["dev"]
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - "${PHPMYADMIN_PORT}:80"
    tmpfs:
      - /tmp
    depends_on:
      - mariadb
