version: "3.8"

services:
  cypress:
    image: cypress/included:9.5.3
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=${CYPRESS_baseUrl:-http://nginx}
    ipc: host
    userns_mode: host
    working_dir: /app
    volumes:
      - ../storage/logs:/app/storage/logs:ro
      - ../tests/e2e:/app/tests/e2e:rw
    tmpfs:
      - /tmp
