name: test

on:
  push:
  schedule:
    - cron: '0 4 */1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ['test', 'test-e2e']
    steps:
      - name: Install Just
        run: curl -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Maintain Composer cache
        uses: actions/cache@v2.1.5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-
      - name: Install dependencies
        run: just install
      - name: Run ${{ matrix.type }}
        run: just ${{ matrix.type }}
